GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/5
###

GET http://localhost:3001/api/persons/5c41c90e84d891c15dfa3431
###

GET http://localhost:3001/api/persons/69495b06c50f49111bbc146e

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "040-123456"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Local Test User"
}
###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Local Test User",
    "number": "040-123456"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Silvana Quejica",
    "number": "0038-7866743"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Nuevo Contacto",
    "number": "957651662233"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "KO",
    "number": "0037-333-3456789"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "KO por phonenumber",
    "number": "0037-33"
}

###
DELETE http://localhost:3001/api/persons/694973ccb02bb4427c40e114